// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx"
import * as $_app from "./routes/_app.tsx"
import * as $api_joke from "./routes/api/joke.ts"
import * as $greet_name_ from "./routes/greet/[name].tsx"
import * as $index from "./routes/index.tsx"
import * as $ASCIIText from "./islands/ASCIIText.tsx"
import * as $Counter from "./islands/Counter.tsx"
import * as $DecryptedText from "./islands/DecryptedText.tsx"
import * as $HeroText from "./islands/HeroText.tsx"
import * as $Noise from "./islands/Noise.tsx"
import * as $Squares from "./islands/Squares.tsx"
import * as $Waves from "./islands/Waves.tsx"
import type { Manifest } from "$fresh/server.ts"

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/ASCIIText.tsx": $ASCIIText,
    "./islands/Counter.tsx": $Counter,
    "./islands/DecryptedText.tsx": $DecryptedText,
    "./islands/HeroText.tsx": $HeroText,
    "./islands/Noise.tsx": $Noise,
    "./islands/Squares.tsx": $Squares,
    "./islands/Waves.tsx": $Waves,
  },
  baseUrl: import.meta.url,
} satisfies Manifest

export default manifest
